from __future__ import annotations

import json
import os
import shutil
import threading
import time
import traceback
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from config import JOBS_FOLDER
from tools.process_zip_generic_rules import (
    DEFAULT_MAX_IMAGES,
    DEFAULT_MAX_TOTAL_EXTRACTED_MB,
    process_batch,
)


VALID_STATUSES = {"queued", "processing", "finished", "failed", "cancelled"}
ACTIVE_STATUSES = {"queued", "processing"}

MAX_ACTIVE_JOBS = int(os.environ.get("EASYOCR_MAX_ACTIVE_JOBS", "10"))
WORKER_SLEEP_SECONDS = float(os.environ.get("EASYOCR_JOB_WORKER_SLEEP_SECONDS", "3"))

JOBS_ROOT = Path(JOBS_FOLDER)

_worker_started = False
_worker_lock = threading.Lock()
_worker_thread: Optional[threading.Thread] = None


def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")


def ensure_jobs_root() -> None:
    JOBS_ROOT.mkdir(parents=True, exist_ok=True)


def make_job_id() -> str:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    suffix = uuid.uuid4().hex[:8]
    return f"{stamp}_{suffix}"


def job_dir(job_id: str) -> Path:
    # Only accept job IDs generated by this service.
    if not job_id or not all(c.isalnum() or c in "_-" for c in job_id):
        raise ValueError("Invalid job_id.")
    return JOBS_ROOT / job_id


def status_path(job_id: str) -> Path:
    return job_dir(job_id) / "job_status.json"


def read_json(path: Path, default: Any = None) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return default
    except json.JSONDecodeError:
        return default


def write_json_atomic(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.replace(path)


def get_job_status(job_id: str) -> Optional[Dict[str, Any]]:
    path = status_path(job_id)
    return read_json(path, default=None)


def update_job_status(job_id: str, **updates) -> Dict[str, Any]:
    status = get_job_status(job_id)
    if not status:
        raise FileNotFoundError(f"Job not found: {job_id}")
    status.update(updates)
    status["updated_at"] = now_iso()
    write_json_atomic(status_path(job_id), status)
    return status


def list_jobs(limit: int = 100) -> List[Dict[str, Any]]:
    ensure_jobs_root()
    jobs = []
    for path in JOBS_ROOT.glob("*/job_status.json"):
        data = read_json(path, default=None)
        if data:
            jobs.append(data)
    jobs.sort(key=lambda x: x.get("created_at", ""), reverse=True)
    return jobs[:limit]


def list_active_jobs() -> List[Dict[str, Any]]:
    return [j for j in list_jobs(limit=1000) if j.get("status") in ACTIVE_STATUSES]


def count_active_jobs() -> int:
    return len(list_active_jobs())


def has_processing_job() -> bool:
    return any(j.get("status") == "processing" for j in list_jobs(limit=1000))


def get_next_queued_job() -> Optional[Dict[str, Any]]:
    queued = [j for j in list_jobs(limit=1000) if j.get("status") == "queued"]
    queued.sort(key=lambda x: x.get("created_at", ""))
    return queued[0] if queued else None


def queue_position(job_id: str) -> Optional[int]:
    queued = [j for j in list_jobs(limit=1000) if j.get("status") == "queued"]
    queued.sort(key=lambda x: x.get("created_at", ""))
    for idx, job in enumerate(queued, start=1):
        if job.get("job_id") == job_id:
            return idx
    return None


def save_uploaded_zip(file: FileStorage, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    file.save(destination)


def create_batch_job(file: FileStorage, submitted_by: Optional[str] = None) -> Dict[str, Any]:
    """Create a queued batch job from an uploaded ZIP file.

    This does not process the job immediately. The background worker will pick it up.
    """
    ensure_jobs_root()

    if count_active_jobs() >= MAX_ACTIVE_JOBS:
        return {
            "status": "error",
            "message": "Queue is full. Please try again later.",
            "active_jobs": count_active_jobs(),
            "max_active_jobs": MAX_ACTIVE_JOBS,
        }

    original_filename = file.filename or "input.zip"
    safe_name = secure_filename(original_filename) or "input.zip"
    if not safe_name.lower().endswith(".zip"):
        return {
            "status": "error",
            "message": "Only ZIP files are accepted for batch jobs.",
        }

    job_id = make_job_id()
    folder = job_dir(job_id)
    folder.mkdir(parents=True, exist_ok=False)

    input_zip = folder / "input.zip"
    save_uploaded_zip(file, input_zip)

    status = {
        "job_id": job_id,
        "status": "queued",
        "allowed_statuses": sorted(list(VALID_STATUSES)),
        "original_filename": original_filename,
        "safe_filename": safe_name,
        "input_zip": "input.zip",
        "result_zip": None,
        "summary_csv": None,
        "summary_json": None,
        "total_images": 0,
        "processed_images": 0,
        "failed_images": 0,
        "skipped_files": 0,
        "queue_position": queue_position(job_id),
        "message": "Job queued.",
        "submitted_by": submitted_by,
        "created_at": now_iso(),
        "updated_at": now_iso(),
        "started_at": None,
        "finished_at": None,
        "error": None,
        "notes": [
            "No database is used. Job metadata is stored in job_status.json.",
            "Only one job is processed at a time.",
            "Maximum active jobs are queued + processing jobs.",
        ],
    }
    write_json_atomic(status_path(job_id), status)
    # Recompute position after status file exists.
    status["queue_position"] = queue_position(job_id)
    write_json_atomic(status_path(job_id), status)
    return status


def copy_batch_outputs_to_job_root(job_id: str) -> None:
    folder = job_dir(job_id)
    output_root = folder / "work" / "output"

    for name in ["summary.csv", "summary.json"]:
        src = output_root / name
        if src.exists():
            shutil.copy2(src, folder / name)

    for sub in ["json", "raw_text", "errors"]:
        src_dir = output_root / sub
        dst_dir = folder / sub
        if src_dir.exists():
            if dst_dir.exists():
                shutil.rmtree(dst_dir)
            shutil.copytree(src_dir, dst_dir)


def process_job(job_id: str) -> None:
    folder = job_dir(job_id)
    input_zip = folder / "input.zip"
    result_zip = folder / "result.zip"
    work_dir = folder / "work"

    update_job_status(
        job_id,
        status="processing",
        started_at=now_iso(),
        message="Processing started.",
        queue_position=0,
        error=None,
    )

    def progress_callback(event: Dict[str, Any]) -> None:
        updates = {
            "message": event.get("message", ""),
        }
        for key in ["total_images", "processed_images", "failed_images", "skipped_files", "current_file"]:
            if key in event:
                updates[key] = event[key]
        update_job_status(job_id, **updates)

    try:
        summary = process_batch(
            input_zip=input_zip,
            output_zip=result_zip,
            work_dir=work_dir,
            max_images=DEFAULT_MAX_IMAGES,
            max_total_extracted_mb=DEFAULT_MAX_TOTAL_EXTRACTED_MB,
            progress_callback=progress_callback,
        )

        copy_batch_outputs_to_job_root(job_id)

        counts = summary.get("counts", {})
        update_job_status(
            job_id,
            status="finished",
            total_images=counts.get("image_files_found", 0),
            processed_images=counts.get("image_files_found", 0),
            failed_images=counts.get("processed_failed", 0),
            skipped_files=counts.get("skipped_files", 0),
            result_zip="result.zip",
            summary_csv="summary.csv",
            summary_json="summary.json",
            message="Job finished.",
            finished_at=now_iso(),
        )

    except Exception as exc:
        error_text = str(exc)
        error_details = {
            "status": "failed",
            "job_id": job_id,
            "error_type": exc.__class__.__name__,
            "error_message": error_text,
            "traceback": traceback.format_exc(),
            "failed_at": now_iso(),
        }
        write_json_atomic(folder / "job_error.json", error_details)
        update_job_status(
            job_id,
            status="failed",
            message=f"Job failed: {error_text}",
            error=error_details,
            finished_at=now_iso(),
        )


def worker_loop() -> None:
    ensure_jobs_root()
    while True:
        try:
            if not has_processing_job():
                next_job = get_next_queued_job()
                if next_job:
                    process_job(next_job["job_id"])
        except Exception:
            # Keep worker alive even if an unexpected error happens.
            traceback.print_exc()
        time.sleep(WORKER_SLEEP_SECONDS)


def start_background_worker() -> None:
    global _worker_started, _worker_thread
    with _worker_lock:
        if _worker_started:
            return
        ensure_jobs_root()
        _worker_thread = threading.Thread(target=worker_loop, name="easyocr-batch-job-worker", daemon=True)
        _worker_thread.start()
        _worker_started = True


def result_file_path(job_id: str, relative_name: str) -> Path:
    allowed = {
        "result.zip": "result.zip",
        "summary.csv": "summary.csv",
        "summary.json": "summary.json",
    }
    if relative_name not in allowed:
        raise ValueError("Invalid result file.")
    return job_dir(job_id) / allowed[relative_name]


def read_job_summary(job_id: str) -> Optional[Dict[str, Any]]:
    return read_json(job_dir(job_id) / "summary.json", default=None)


def get_job_result_rows(job_id: str) -> List[Dict[str, Any]]:
    """Return rows for HTML result table from summary.json."""
    summary = read_job_summary(job_id)
    if not summary:
        return []
    return summary.get("files", []) or []


def get_per_image_json_path(job_id: str, output_stem: str) -> Path:
    safe = secure_filename(output_stem or "")
    if not safe:
        raise ValueError("Invalid output_stem.")
    return job_dir(job_id) / "json" / f"{safe}.json"


def find_input_image_path(job_id: str, output_stem: str, filename: Optional[str] = None) -> Optional[Path]:
    """Find processed input image for preview.

    The CLI extracts images to work/input_images and uses safe output stems.
    Prefer output_stem because Thai filenames can sanitize to generic/numeric
    names such as "9.jpg", which may belong to a different row.
    """
    folder = job_dir(job_id) / "work" / "input_images"
    if not folder.exists():
        return None

    candidates = []
    safe_stem = secure_filename(output_stem or "")
    if safe_stem:
        for ext in [".jpg", ".jpeg", ".png", ".webp", ".bmp"]:
            candidates.append(folder / f"{safe_stem}{ext}")

    if filename:
        safe_filename = secure_filename(filename)
        if safe_filename:
            candidates.append(folder / safe_filename)

    for path in candidates:
        if path.exists() and path.is_file():
            return path

    # Fallback: scan by stem.
    if safe_stem:
        for path in folder.iterdir():
            if path.is_file() and path.stem == safe_stem:
                return path

    return None


def reset_active_jobs(reason: str = "Manually reset from UI/API") -> Dict[str, Any]:
    """Mark queued/processing jobs as cancelled.

    This is intentionally non-destructive: it does not delete result files or job
    folders. If a Python worker is truly stuck inside EasyOCR, stop/restart the
    service first, then use this to clear stale queued/processing statuses.
    """
    changed = []
    for job in list_jobs(limit=1000):
        if job.get("status") not in ACTIVE_STATUSES:
            continue
        job_id = job.get("job_id")
        if not job_id:
            continue
        updated = update_job_status(
            job_id,
            status="cancelled",
            message=reason,
            queue_position=None,
            finished_at=now_iso(),
            error={
                "type": "manual_reset",
                "message": reason,
                "reset_at": now_iso(),
            },
        )
        changed.append({
            "job_id": job_id,
            "previous_status": job.get("status"),
            "new_status": updated.get("status"),
        })

    return {
        "status": "success",
        "cancelled_jobs": changed,
        "cancelled_count": len(changed),
        "message": f"Cancelled {len(changed)} active job(s).",
    }


def delete_job(job_id: str) -> None:
    folder = job_dir(job_id)
    if folder.exists():
        shutil.rmtree(folder)
